SELECT 
  SUBSTRING_INDEX(SUBSTRING_INDEX(target_col, ',', numbers.n), ',', -1) AS flattened_value
  , name
FROM
  combined_table
JOIN (
  SELECT
    a.N + b.N * 10 + 1 AS n
  FROM
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
  ORDER BY
    n
) numbers
ON
  CHAR_LENGTH(target_col) - CHAR_LENGTH(REPLACE(target_col, ',', '')) >= numbers.n - 1
ORDER BY
  name;
